### ISSUE TITLE
Installing PPA Fails (GPG error)

### ISSUE THREAD

**Issue by HCrane** [PapirusDevelopmentTeam/arc-kde#54]
Hey guys!

Apperantly when I tried to install arc-kde on a new Debian 9 installation i got this error:

```
➜ sudo add-apt-repository ppa:papirus/arc-kde
 Arc KDE - This is a port of the popular GTK theme Arc for Plasma 5 desktop with a few additions and extras.

To install Arc KDE from this PPA, run these commands on a terminal:

sudo add-apt-repository ppa:papirus/arc-kde
sudo apt-get update
sudo apt-get install arc-kde
 More info: https://launchpad.net/~papirus/+archive/ubuntu/arc-kde
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpkzljpth4/pubring.gpg' created
gpg: /tmp/tmpkzljpth4/trustdb.gpg: trustdb created
gpg: key E58A9D36647CAE7F: public key "Launchpad PPA for Papirus" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.browser'

```

I suppose it has something to do with the fact that the papirus gpg key is empty. How can I fix this?

Best wishes

**Comment by SmartFinn** [comment]
The commands for Ubuntu and her derivatives only. Try the following commands to install this package in Debian:

```sh
sudo sh -c "echo 'deb http://ppa.launchpad.net/papirus/papirus/ubuntu xenial main' > /etc/apt/sources.list.d/arc-kde-ppa.list"

sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com E58A9D36647CAE7F
sudo apt-get update
sudo apt-get install arc-kde
```
